Go to https://julialang.org/downloads/Install julia stable release according to your system specsOpen Julia (Allow Julia to access the Terminal)println("Hello World")
using PkgPkg.add("IJulia")
Open anaconda and New -> open Juia_version

Julia is a modern, expressive, high-performance programming language designed for scientific
computation and data manipulation.

Launched in 2012, Julia is an open-source language that combines the interactivity and syntax of 'scripting' languages, such as Python, Matlab and R, with the speed of 'compiled' languages such as Fortran and C

numerical performance of python and R can be disappointing
It proves as an excellent option for numerical computing and can solve bigger & complex codes in much less time. 
Julia was primarily designed keeping in mind its high-speed performance that is incredibly faster than any other. Its programs are compiled to the efficient native code for the multiple platforms via LLVM. 

superb support for parallelization
Multiple Dispatch Julia employs multiple dispatch as a paradigm which makes it fairly generic and therefore, easy to express several object-oriented and functional programming patterns. While Julias dispatch is not only faster, it also makes for its inheritance to be viable inside of Julia as well as makes a function extendable. It also serves great in case of package extensions.

Google says its great for ML based on Usabiliy + Technical Merit

Forward mode automatic differentiation AutoDiff

Symbolic Mahematics in Julia via symata is cool


In [1]:
println("hello world")


hello world


In [2]:
H = [0 1 -2 1; 2 -1 3 0]
H'

4×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
  0   2
  1  -1
 -2   3
  1   0

In [3]:
# Matrix-vector multiplication
A = [0 2 -1; -2 1 1]
x = [2, 1, -1]
A*x

2-element Array{Int64,1}:
  3
 -4

In [4]:
using LinearAlgebra

In [5]:
rank(diagm([1, 0, 2]))

2

In [6]:
A = [1 0; 1 -2]; b = [32; -4];
A \ b #This is faster than x=inv(A)*b, which first computes the inverse of A and then multiplies it with b.

#If A is square, this syntax solves the linear system  Ax=b . 
#Therefore, it returns x such that A * x = b. If A is rectangular, 
#it solves for the least-squares solution to the problem.

2-element Array{Float64,1}:
 32.0
 18.0

In [33]:
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]
sB = Symmetric(B)
x = [1; 2; 3]
sB\x
#The \ operation here performs the linear solution. The left-division operator is pretty powerful 
#and it's easy to write compact, readable code that is flexible enough to solve all sorts of systems of linear equations.

3-element Array{Float64,1}:
 -1.7391304347826084
 -1.1086956521739126
 -1.4565217391304346

In [7]:
"""function back_subst(R,b)
n = length(b)
x = zeros(n)
    for i=n:-1:1
    x[i] = (b[i] - R[i,i+1:n]'*x[i+1:n]) / R[i,i]
    end
    return x
    end;

x = back_subst(A,b);
#norm(A*x-b)

A*x-b"""

"function back_subst(R,b)\nn = length(b)\nx = zeros(n)\n    for i=n:-1:1\n    x[i] = (b[i] - R[i,i+1:n]'*x[i+1:n]) / R[i,i]\n    end\n    return x\n    end;\n\nx = back_subst(A,b);\n#norm(A*x-b)\n\nA*x-b"

Matrix division using a polyalgorithm. For input matrices A and B, the result X is such that A*X == B when A is square. The solver that is used depends upon the structure of A. If A is upper or lower triangular (or diagonal), no factorization of A is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular A the result is the minimum-norm least squares solution computed by a pivoted QR factorization of A and a rank estimate of A based on the R factor.

When A is sparse, a similar polyalgorithm is used. For indefinite matrices, the LDLt factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

In [8]:
M = [1 0 0; 0 1 0; 1 0 0]

nullspace(M) #Basis for nullspace of M.

3×1 Array{Float64,2}:
 0.0
 0.0
 1.0

In [9]:
A = [1.5 2 -4; 3 -1 -6; -10 2.3 4]

3×3 Array{Float64,2}:
   1.5   2.0  -4.0
   3.0  -1.0  -6.0
 -10.0   2.3   4.0

In [10]:
factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
  1.0    0.0       0.0
 -0.15   1.0       0.0
 -0.3   -0.132196  1.0
U factor:
3×3 Array{Float64,2}:
 -10.0  2.3     4.0
   0.0  2.345  -3.4
   0.0  0.0    -5.24947

In [11]:
A = [1 2 3; 4 1 6; 7 8 1]

3×3 Array{Int64,2}:
 1  2  3
 4  1  6
 7  8  1

In [12]:
tr(A)#Matrix trace. Sums the diagonal elements of M.

3

In [13]:
det(A)

104.0

In [14]:
T = transpose(A)

3×3 Transpose{Int64,Array{Int64,2}}:
 1  4  7
 2  1  8
 3  6  1

In [15]:
inv(A)#Matrix inverse. Computes matrix N such that A * N = I, where I is the identity matrix. Computed by solving the left-division N = A \ I.

3×3 Array{Float64,2}:
 -0.451923   0.211538    0.0865385
  0.365385  -0.192308    0.0576923
  0.240385   0.0576923  -0.0673077

In [16]:
A = [-4. -17.; 2. 2.]

2×2 Array{Float64,2}:
 -4.0  -17.0
  2.0    2.0

Matrix factorization type of the eigenvalue/spectral decomposition of a square matrix A. This is the return type of eigen, the corresponding matrix factorization function.

If F::Eigen is the factorization object, the eigenvalues can be obtained via F.values and the eigenvectors as the columns of the matrix F.vectors. (The kth eigenvector can be obtained from the slice F.vectors[:, k].)

Iterating the decomposition produces the components F.values and F.vectors.

In [17]:
F = eigen([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
  1.0
  3.0
 18.0
vectors:
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [18]:
eigvals(A)

λ = eigvals(A)  # This is fun , type \lambda + <tab>.  Other characters work too!
λ

2-element Array{Complex{Float64},1}:
 -1.0 - 5.0im
 -1.0 + 5.0im

In [19]:
eigvecs(A)

2×2 Array{Complex{Float64},2}:
  0.945905-0.0im        0.945905+0.0im
 -0.166924+0.278207im  -0.166924-0.278207im

In [20]:
diag_matrix = [1 0; 0 4]
eigvals(diag_matrix)

2-element Array{Float64,1}:
 1.0
 4.0

In [21]:
A = [3.0 -6.0; 4.0 -8.0; 0.0 1.0]

3×2 Array{Float64,2}:
 3.0  -6.0
 4.0  -8.0
 0.0   1.0

In [22]:
F = qr(A)

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.6   0.0   0.8
 -0.8   0.0  -0.6
  0.0  -1.0   0.0
R factor:
2×2 Array{Float64,2}:
 -5.0  10.0
  0.0  -1.0

Matrix factorization type of the singular value decomposition (SVD) of a matrix A. This is the return type of svd(_), the corresponding matrix factorization function.

If F::SVD is the factorization object, U, S, V and Vt can be obtained via F.U, F.S, F.V and F.Vt, such that A = U * Diagonal(S) * Vt. The singular values in S are sorted in descending order.

Iterating the decomposition produces the components U, S, and V.

In [23]:
#SVD


A = rand(4,3);



In [24]:
F = svd(A); # Store the Factorization Object
F

SVD{Float64,Float64,Array{Float64,2}}
U factor:
4×3 Array{Float64,2}:
 -0.618703   0.116813   0.136644
 -0.632796  -0.623247  -0.275902
 -0.282324   0.694139  -0.623477
 -0.370228   0.340719   0.718667
singular values:
3-element Array{Float64,1}:
 1.664744813875574
 0.8693144761423958
 0.22211888779408687
Vt factor:
3×3 Array{Float64,2}:
 -0.697268  -0.48165   -0.530878
 -0.282629   0.865342  -0.413888
  0.65874   -0.13855   -0.739503

In [25]:
A ≈ F.U * Diagonal(F.S) * F.Vt


true

In [26]:
U, S, V = F; # destructuring via iteration
A ≈ U * Diagonal(S) * V'

true

In [27]:
Uonly, = svd(A); # Store U only

Uonly == U

true

Solving least squares problems
Julia uses the backslash operator to denote the least squares approximate solution: xhat = A\b.

In [28]:
A = randn(100,20); b = randn(100);
x1 = A\b; # Least squares using backslash operator
x2 = inv(A'*A)*(A'*b); # Using formula
x3 = pinv(A)*b; # Using pseudo-inverse
Q, R = qr(A);
Q = Matrix(Q);
x4 = R\(Q'*b); # Using QR factorization
norm(x1-x2)

4.279032816527531e-16

In [29]:
norm(x2-x3)

5.621817332665476e-16

In [30]:
norm(x3-x4)

6.547880661026478e-16

Matrix least squares. Let’s solve multiple least squares problems with the same
matrix A and different vectors b.

In [31]:
A = randn(1000,100); B = randn(1000,10);
X = A\B;
# Check that third column of X is least squares solution
# with third column of B
x3 = A\B[:,3];
norm(X[:,3]-x3)

1.2632849031376745e-16

In [ ]:
#REFERENCES

#https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/
#https://juliabyexample.helpmanual.io/
#https://github.com/ablaom/MachineLearningInJulia2020/blob/master/tutorials.jl
#https://julia.quantecon.org/tools_and_techniques/linear_algebra.html
#http://vmls-book.stanford.edu/vmls-julia-companion.pdf
#https://www.youtube.com/watch?v=4igzy3bGVkQ
